from __future__ import absolute_import

from collections import namedtuple

DESCRIBE_OPT = "--describe"
OPTIONS_OPT = "--options"
DEFAULT_STREAM = "default"

StormTuple = namedtuple('StormTuple', "id comp stream task values")


def is_tick(tup):
    """Tick tuples (generated by Storm; introduced 0.8) are defined as being
    from the __system component and __tick stream.
    """
    return tup.comp == '__system' and tup.stream == '__tick'


class StormWentAwayError(Exception):

    def __init__(self):
        message = "Got EOF while reading from Storm"
        super(StormWentAwayError, self).__init__(message)


from pyleus.storm.bolt import Bolt, SimpleBolt
from pyleus.storm.spout import Spout

_ = [Bolt, SimpleBolt, Spout] # pyflakes
